### ISSUE TITLE
test-c fails on Mac

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#345]
OK, the `static` trick didn't work, `wait` needs a rename. 
```
[12:15:46] 1 numbbo$ ./do.py test-c
AML	['code-experiments/src/coco_generics.c', 'code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/c/coco.c
COPY	code-experiments/src/coco.h -> code-experiments/build/c/coco.h
COPY	code-experiments/build/c/coco.c -> code-experiments/examples/bbob2009-c-cmaes/coco.c
COPY	code-experiments/build/c/coco.h -> code-experiments/examples/bbob2009-c-cmaes/coco.h
WRITE	code-experiments/build/c/REVISION
WRITE	code-experiments/build/c/VERSION
MAKE	clean in code-experiments/build/c
COPY	Makefile.in -> Makefile
MAKE	all in code-experiments/build/c
COPY	Makefile.in -> Makefile
COPY	code-experiments/test/unit-test/lib/macosx/libcmocka.dylib -> code-experiments/test/unit-test/libcmocka.dylib
COPY	code-experiments/build/c/coco.c -> code-experiments/test/unit-test/coco.c
COPY	code-experiments/src/coco.h -> code-experiments/test/unit-test/coco.h
MAKE	clean in code-experiments/test/unit-test
COPY	Makefile.in -> Makefile
MAKE	all in code-experiments/test/unit-test
COPY	Makefile.in -> Makefile
RUN	./unit_test in code-experiments/test/unit-test
COPY	code-experiments/build/c/coco.c -> code-experiments/test/integration-test/coco.c
COPY	code-experiments/src/coco.h -> code-experiments/test/integration-test/coco.h
COPY	code-experiments/src/bbob2009_testcases.txt -> code-experiments/test/integration-test/bbob2009_testcases.txt
MAKE	clean in code-experiments/test/integration-test
COPY	Makefile.in -> Makefile
MAKE	all in code-experiments/test/integration-test
COPY	Makefile.in -> Makefile
ERROR: return value=2
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o test_coco.o test_coco.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
code-experiments/src/logger_biobj_avl_tree.c:119:35: warning: missing field 'next' initializer [-Wmissing-field-initializers]
const avl_node_t avl_node_0 = { 0 };
                                  ^
code-experiments/src/logger_biobj_avl_tree.c:120:35: warning: missing field 'head' initializer [-Wmissing-field-initializers]
const avl_tree_t avl_tree_0 = { 0 };
                                  ^
code-experiments/src/logger_biobj_avl_tree.c:121:45: warning: missing field 'deallocate' initializer [-Wmissing-field-initializers]
const avl_allocator_t avl_allocator_0 = { 0 };
                                            ^
3 warnings generated.
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o test_coco coco.o test_coco.o -lm  
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o test_instance_extraction.o test_instance_extraction.c
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o test_instance_extraction coco.o test_instance_extraction.o -lm  
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o test_biobj.o test_biobj.c
test_biobj.c:12:13: error: static declaration of 'wait' follows non-static declaration
static void wait (unsigned int secs) {
            ^
/usr/include/sys/wait.h:248:7: note: previous declaration is here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
        ^
test_biobj.c:72:8: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'int *' [-Wint-conversion]
  wait(2); /* So that the directory removal is surely finished */
       ^
/usr/include/sys/wait.h:248:17: note: passing argument to parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
                  ^
1 warning and 1 error generated.
make: *** [test_biobj.o] Error 1

Traceback (most recent call last):
  File "./do.py", line 589, in <module>
    main(sys.argv[1:])
  File "./do.py", line 575, in main
    elif cmd == 'test-c': test_c()
  File "./do.py", line 63, in test_c
    build_c_integration_tests()
  File "./do.py", line 134, in build_c_integration_tests
    make("code-experiments/test/integration-test", "all")
  File "/Users/hansen/git/numbbo/code-experiments/tools/cocoutils.py", line 190, in make
    universal_newlines=True)
  File "/Users/hansen/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'make', 'all']' returned non-zero exit status 2
```

**Comment by ttusar** [comment]
The function is renamed. I'm keeping the issue open until the test succeeds.

**Comment by nikohansen** [comment]
Test succeeded, then it becomes my prerogative to close it :-)
